#!/bin/bash

echo "Building openssl for the library"
chmod +x ./openssl/Configure

chmod +x ./scripts/compile-deps-win
chmod +x ./scripts/compile-deps-nix

if [[ " $* " == *" --windows "* ]]; then
  ./scripts/compile-deps-win
  cmake -DCMAKE_TOOLCHAIN_FILE=./scripts/mingw-w64-x86_64.cmake .
else
  ./scripts/compile-deps-nix
  cmake .
fi

make